# - name: Create Azure VM
#   hosts: localhost
#   connection: local
#   vars:
#     resource_group: lab-ansbile
#     vm_name: testvm
#     location: eastus
# - name: Using Azure collection
#   hosts: localhost
#   collections:
#     - azure.azcollection
#   tasks:
#     - azure_rm_storageaccount:
#         resource_group: myResourceGroup
#         name: myStorageAccount
#         account_type: Standard_LRS

- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: testing
      location: "eastus"

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: testing
      name: testvn001
      address_prefixes_cidr:
          - "10.1.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: testing
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: testing
      allocation_method: Static
      name: publicip001

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: testing
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: testing
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: testing
      name: testvm001
      vm_size: Standard_DS1_v2
      storage_account: testaccount001
      storage_container: testvm001
      storage_blob: testvm001.vhd
      admin_username: admin
      admin_password: admin
      network_interfaces: testnic001
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest