- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: Testing
      location: eastus
    
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: Testing
      name: testact598666
      account_type: Standard_LRS

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: testvn001
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001

  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: Testing
      allocation_method: Static
      name: publicip001
    register: output_ip_address

  # - name: Pegando o ip publico
  #   copy:
  #     content: "{{ output_ip_address.state.ip_address }}."
  #     dest: /tmp/teste
    
  - name: Prepando o arquivo hosts com ip publico do maquina
    shell: echo "[ansible]\n{{ output_ip_address.state.ip_address}}" > /projeto/ansible/hosts


  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: Testing
      name: secgroup001
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: Testing
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: Testing
      name: testvm001
      vm_size: Standard_A1_v2
      storage_account: testact598666
      storage_container: testvm001
      storage_blob: testvm001.vhd
      admin_username: ditiepc123
      # admin_password: diti@2302155
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /tmp/test/authorized_keys
          key_data: test.pem
      network_interfaces: testnic001
      image:
        offer: RHEL
        publisher: RedHat
        sku: 8
        version: latest

  
