---
- name: Deletando Resource Group
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Deleting resource group - Testing
      azure_rm_resourcegroup:
        name: Testing
        force_delete_nonempty: true
        state: absent
      register: rg
    - debug:
        var: rg